Feature/appbarbottom
Xerox-Parc/material-components-demo pull request #38
Opened 2020-05-30 16:51 UTC by Ivan-Palm

2020-06-05 18:28 UTC, Sph00b commented
Just some requests before the code review:

- Move the bottom app from the ScrollView to the main CoordinatorLayout
- Add some actions, the official documentation advises against the use of bottom app bar on screens with one or no actions (other than a FAB)
- The official documentation advises against the use of navigation actions in a bottom app bar.

2020-06-05 18:31 UTC, buracchi requested changes
Just some requests before the code review:

- Move the bottom app from the ScrollView to the main CoordinatorLayout
- Add some actions, the official documentation advises against the use of bottom app bar on screens with one or no actions (other than a FAB)
- The official documentation advises against the use of navigation actions in a bottom app bar.

2020-06-07 13:59 UTC, buracchi requested changes
If you use the search icon then you should implement a SearchView. IMO you should just change the icon and mantain the toast in the code.
The app bar should be opaque and the menu should be affected by the theme.

2020-06-07 13:59 UTC, Sph00b commented on app/src/main/res/drawable/ic_expand_less_black_24dp.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
This icon is unused, delete it.

2020-06-07 13:59 UTC, Sph00b commented on app/src/main/res/drawable/ic_more_vert_24dp.xml
> +<vector android:height="24dp" android:tint="#FFFFFF"
This icon is unused, delete it.

2020-06-07 13:59 UTC, Sph00b commented on app/src/main/res/drawable/ic_format_align_justify_24dp.xml
> +<vector android:height="24dp" android:tint="#000000"
You had chosen the wrong icon.

2020-06-10 23:04 UTC, buracchi approved these changes
I'll fix it personally in the next release

2020-06-10 23:04 UTC, Sph00b commented on app/src/main/res/drawable/ic_view_headline_24dp.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Delete this unused icon

2020-06-10 23:04 UTC, Sph00b commented on app/src/main/res/layout/activity_app_bar_bottom.xml
> +    <com.google.android.material.floatingactionbutton.FloatingActionButton
Move the FAB and the BottomAppBar to  the bottom to avoid graphic glitch

2020-06-10 23:04 UTC, Sph00b commented on app/src/main/java/com/xeroxparc/materialcomponentsdemo/ui/component/appbarbottom/AppBarBottomActivity.java
> +    binding.fab.setOnClickListener(l->{
Replace with expression lambda

2020-06-10 23:07 UTC, merged